language: ruby
rvm:
  - 1.8.7
  #- 1.9.2
  - 1.9.3
  #- 2.0.0
  - 2.1.1
  #- jruby-18mode
  - jruby-19mode
  #- jruby-20mode
  #- rbx-18mode
  #- rbx-19mode
  #- rbx-20mode
script: bundle exec rspec
branches:
  only:
    - master
  #except:
  #  - master
