
name: test

on: [ push, pull_request ]

jobs:

  test:

    if: " ! (contains(github.event.head_commit.message, 'skip ci') || contains(github.event.head_commit.message, 'ci skip'))"

    name: ${{matrix.ruby}} on ${{matrix.os}}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby: [
          '2.5', '2.7', '3.1', '3.2', '3.3', '3.4',
          'jruby-9.4' ]
        experimental: [ false ]
      fail-fast: false
    runs-on: ${{matrix.os}}
    continue-on-error: ${{matrix.experimental}}

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true # 'bundle install' and cache
      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: bundle exec rspec --force-color --format documentation

